imdbclone/urls.py
from django.contrib import admin  
from django.urls import path  
from actor import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

actor/models.py
from django.db import models

# Create your models here.
 
class Actor(models.Model):  
    edob = models.CharField(max_length=8)  
    ename = models.CharField(max_length=100)  
    esex = models.CharField(max_length=6)  
    ebio = models.CharField(max_length=600)  
    class Meta:  
        db_table = "actor"  

actor/forms.py
from django import forms  
from actor.models import Actor  
class ActorForm(forms.ModelForm):  
    class Meta:  
        model = Actor  
        fields = "__all__"  

actor/views.py
from django.shortcuts import render, redirect  
from actor.forms import ActorForm  
from actor.models import Actor  
# Create your views here.  
def emp(request):  
    if request.method == "POST":  
        form = ActorForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = EmployeeForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    actors = Actors.objects.all()  
    return render(request,"show.html",{'actors':actors})  
def edit(request, id):  
    actor = Actor.objects.get(id=id)  
    return render(request,'edit.html', {'actor':actor})  
def update(request, id):  
    actor = Actor.objects.get(id=id)  
    form = ActorForm(request.POST, instance = actor)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'actor': actor})  
def destroy(request, id):  
    actor = Actor.objects.get(id=id)  
    actor.delete()  
    return redirect("/show")  

actor/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{actor.id}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor DOB:</label>  
    <div class="col-sm-4">  
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ actor.eid }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ actor.ename }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Sex:</label>  
    <div class="col-sm-4">  
        <input type="sex" name="esex" id="id_esex" required maxlength="254" value="{{ actor.esex }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Bio:</label>  
    <div class="col-sm-4">  
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ actor.ebio }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

actor/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/emp">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor DOB:</label>  
    <div class="col-sm-4">  
      {{ form.edob }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Sex:</label>  
    <div class="col-sm-4">  
      {{ form.esex }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Actor Bio:</label>  
    <div class="col-sm-4">  
      {{ form.ebio }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

actor/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Actor Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Actor DOB</th>  
        <th>Actor Name</th>  
        <th>Actor Sex</th>  
        <th>Actor Bio</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for actor in actors %}  
    <tr>  
        <td>{{ actor.edob }}</td>  
        <td>{{ actor.ename }}</td>  
        <td>{{ actor.esex }}</td>  
        <td>{{ actor.ebio }}</td>  
        <td>  
            <a href="/edit/{{ actor.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ actor.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
</body>  
</html>  